### ISSUE TITLE
Release ceramic 0.8.0

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/ceramic#47]
Prepare for release:

- [x] decouple tile download from read
- [x] allow use of terra objects for 'loc'
- [x] remove dep on rgdal completely (https://github.com/hypertidy/ceramic/issues/45)
- [x] sort out where gdalwmscache ends up (temp or user-controlled)
- [x] support wkt/geos  #48 
- [x] fix tile getter #49 
- [x] clear the milestones.https://github.com/hypertidy/ceramic/milestone/1
- [x] remove raster and use terra  077fbef
- [x] think about disruption caused by move to terra ...
- [ ] ~consider matching projection of input query, because we aren't know about tiles for raster load (??)~ no do this elsewhere
- [x] document that the read on demand is not the same as the tile downloads
- [x] consider read the tiles, done 4713726b375adb96852d14bf50ab31f5a78e8361

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_ceramic.html)
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [ ] `devtools::build_readme()`
* [ ] `urlchecker::url_check()`
* [ ] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`
* [ ] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [ ] `usethis::use_version('minor')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `git push`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by mdsumner** [comment]
don biatch
